### ISSUE TITLE
Listenansicht .. Datum reihenfolge

### ISSUE THREAD

**Issue by fw-thomas** [phoebusryan/rex4_custom_firedepartment#10]
Die Datumfolge ist von z.Z. absteigend eingerichtet .

Sprich am oberster stelle ist der 01.02.2015 und unten der 03.01.2015

![einsatz reihenfolge](https://cloud.githubusercontent.com/assets/12305603/14221686/09728dc6-f869-11e5-8692-423db8f2d40b.jpg)

**Comment by phoebusryan** [comment]
Und du hättest es gerne anders rum? Also die ältesten ganz oben und die neusten ganz unten?

Dann müsstest du in der nachfolgenden Zeile ganz am schluss das DESC durch ASC ersetzen:
https://github.com/phoebusryan/rex4_custom_firedepartment/blob/master/classes/class.rex_firedepartment.inc.php#L81
