### ISSUE TITLE
leere seite

### ISSUE THREAD

**Issue by fw-thomas74** [phoebusryan/rex4_custom_firedepartment#5]
Installation durch gelaufen
Es wird allerdings nur eine weisse Seite dann angezeigt wenn ich das addon Stätten will

**Comment by phoebusryan** [comment]
Eine weisse Seite kommt, wenn du in der linken Spalte auf "Feuerwehr Einsätze" klickst? Evtl. ist das dann doch noch ein PHP-Problem. Kannst du mal in der /redaxo/index.php ganz oben (nach dem <?php) folgendes Einfügen:

`error_reporting(E_ALL);  
ini_set('display_errors',1);`

..und schauen ob du eine genauere Fehlermeldung bekommst?

**Comment by phoebusryan** [comment]
Ich habe, ich habe das Problem gefunden und korrigiert:
https://github.com/phoebusryan/rex4_custom_firedepartment/blob/master/pages/index.inc.php#L11-L12

Die beiden Zeilen müsstest du im /redaxo/include/addons/rex_firedepartment/pages/index.inc.php austauschen.

**Comment by fw-thomas** [comment]
Top das geht nun
