### ISSUE TITLE
Einstellung ist leer

### ISSUE THREAD

**Issue by fw-thomas** [phoebusryan/rex4_custom_firedepartment#6]
unter den Punk Einstellung ist leider nix zu sehen ..

**Comment by fw-thomas** [comment]
so umbestellt

REDAXO: 4.6.1
PHP: 5.6.17

**Comment by fw-thomas** [comment]
nun ist alles da ..

**Comment by phoebusryan** [comment]
Ach, du kannst doch auf PHP 5.6 umstellen? Da hätte ich mir einiges sparen können. Aber gut, dass es jetzt läuft.
