### ISSUE TITLE
Einsatzende

### ISSUE THREAD

**Issue by fw-thomas74** [phoebusryan/rex4_custom_firedepartment#8]
Kann nicht aus dem Kalender und Uhrzeit übernommen werden, bzw. es wird nicht ins Feld eingetragen

**Comment by phoebusryan** [comment]
Stimmt, da war noch ein Fehler drin. Hier der Fix:
https://github.com/phoebusryan/rex4_custom_firedepartment/blob/master/files/scripts.js#L11-L12

Nach dem Ändern des Files musst du das Addon re-installieren.
